### ISSUE TITLE
graci fails to compile

### ISSUE THREAD

**Issue by chburger** [schuurman-group/graci#31]
I obtain the following error message when I try to compile graci with the Intel ifort compiler Version 19.1.0.166 Build 20191121

/home/graci/graci/lib/bitci/src/common/utils/radixsort.f90(49): error #6975: A kind-param must be a digit-string or a scalar-int-constant-name.   [IB]
                a = shiftr(a , 8_ib)
---------------------------------^
compilation aborted for /home/graci/graci/lib/bitci/src/common/utils/radixsort.f90 (code 1)
make[2]: *** [CMakeFiles/bitsi.dir/build.make:407: CMakeFiles/bitsi.dir/src/common/utils/radixsort.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:99: CMakeFiles/bitsi.dir/all] Error 2

**Comment by spneville** [comment]
This bug has been fixed. Please pull and re-build

**Comment by chburger** [comment]
Thanks so much! Is there an easy way to include atoms with ecps? I have seen that I have to modify molecule.py to include further elements and then probably scf.py?
